services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: java_crud
      MYSQL_ROOT_PASSWORD: 'root'

  db_adminer_mysql:
    container_name: db_adminer_mysql
    image: adminer
    restart: always
    ports:
      - '8081:8080'